// src/routes/dashboard.svelte
<script context="module" lang="ts">
  import gameInfo from "../game-info";

  export async function preload() {
    return {
      gameInfo: await gameInfo.fetch(this.fetch),
    };
  }
</script>

<script lang="ts">
  import DataTable, { Body, Cell, Head, Row } from "@smui/data-table";
  import { derived } from "svelte/store";
  import ItemButton from "../components/ItemButton.svelte";
  import type { GameInfo, Item } from "../game-info";
  import { seasonNames } from "../names";
  import save from "../save-info";
  import type { SaveInfo } from "../save-info";

  export let gameInfo: GameInfo;

  interface Birthday {
    villager: string;
    hearts: number;
    maxHearts: number;
    date: string;
    bestGifts: Item[];
  }

  let birthdays = derived<typeof save, Birthday[]>(
    save,
    ($save: SaveInfo | null, set: (value: Birthday[]) => void) => {
      if ($save !== null) {
        set(
          Object.values(gameInfo.villagers)
            .sort(
              (a, b) =>
                ((a.birthDate - $save.currentDate + 112) % 112) -
                ((b.birthDate - $save.currentDate + 112) % 112)
            )
            .map((villager) => ({
              villager: villager.name,
              date: villager.birthday,
              hearts: $save.relationships.get(villager.name)?.hearts ?? 0,
              maxHearts:
                $save.relationships.get(villager.name)?.maxHearts ??
                (villager.datable ? 8 : 10),
              bestGifts: villager.bestGifts,
            }))
        );
      }
    }
  );

  let seasonalItems = derived<typeof save, Item[]>(
    save,
    ($save: SaveInfo | null, set: (value: Item[]) => void) => {
      if ($save !== null) {
        set(
          [...gameInfo.shipping, ...gameInfo.fish].filter(
            (item) =>
              typeof item.seasons !== "undefined" &&
              item.seasons.includes(["spring", "summer", "fall", "winter"][$save.currentSeason]) &&
              !$save.collectedItems.includes(item.id) &&
              Object.values(item.seasons).filter((value) => value).length < 3
          )
        );
      }
    }
  );
</script>

<style lang="scss">
  @use '@material/typography/mixins' as typography;
  @use '@material/card/mdc-card';

  .best-gifts {
    display: flex;
    flex-direction: row;

    :global(button:not(:last-of-type)) {
      margin-right: 8px;
    }
  }

  .hearts {
    display: flex;
    flex-direction: row;

    img {
      user-select: none;

      &:not(:last-of-type) {
        margin-right: 2px;
      }
    }
  }

  .title {
    margin: 20px 20px 0.5em;
  }

  h1 {
    @include typography.mdc-typography("headline4");
  }

  h2 {
    @include typography.mdc-typography("headline6");
  }

  .container {
    display: grid;
    gap: 24px;
    grid-template-areas:
      "b"
      "s";

    @media only screen and (min-width: 1250px) {
      grid-template-areas: "b s";
      grid-template-columns: minmax(0, 1fr) auto;
      grid-template-rows: min-content;
    }

    padding: 0 20px 20px;
  }

  .seasonal {
    display: flex;
    flex-flow: column nowrap;

    grid-area: s;

    padding: 16px;

    .seasonal-items {
      display: grid;
      grid-auto-flow: row;
      grid-auto-rows: 64px;
      grid-template-columns: repeat(auto-fill, 64px);
      gap: 8px;

      flex-grow: 1;

      @media only screen and (min-width: 1250px) {
        grid-template-columns: repeat(2, 64px);
      }
    }
  }
</style>

<svelte:head>
  <title>Dashboard | Stardew Completionist</title>
</svelte:head>

<h1 class="title">Dashboard</h1>
{#if $save !== null}
  <div class="container">
    <DataTable>
      <Head>
        <Row>
          <Cell>Villager</Cell>
          <Cell>Hearts</Cell>
          <Cell>Birthday</Cell>
          <Cell>Best Gifts</Cell>
        </Row>
      </Head>
      <Body>
        {#each $birthdays as birthday}
          <Row>
            <Cell>{birthday.villager}</Cell>
            <Cell>
              <div class="hearts">
                {#each [...Array(birthday.maxHearts).keys()] as i}
                  <img
                    alt="heart"
                    src="heart-{birthday.hearts >= i + 1 ? 'filled' : 'outline'}.png" />
                {/each}
              </div>
            </Cell>
            <Cell>{birthday.date}</Cell>
            <Cell>
              <div class="best-gifts">
                {#each birthday.bestGifts as item}
                  <ItemButton {item} scale={item.isCraftable ? 1 : 2} />
                {/each}
              </div>
            </Cell>
          </Row>
        {/each}
      </Body>
    </DataTable>
    <div class="mdc-card mdc-card--outlined seasonal">
      <h2>{seasonNames.get($save.currentSeason)}</h2>
      <div class="seasonal-items">
        {#each $seasonalItems as item}
          <ItemButton {item} scale={item.isCraftable ? 2 : 3} />
        {/each}
      </div>
    </div>
  </div>
{/if}

// stardew-completionist/src/app/dashboard/dashboard.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { GameInfoService, Item, seasonNames } from '../data/game-info.service';
import { SaveInfo, SaveInfoService } from '../data/save-info.service';
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator } from '@angular/material/paginator';
import { range } from '../friendship/friendship.component';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {
  seasonalItems: Item[];
  birthdays: Birthday[];
  upcomingBirthdays = new MatTableDataSource<Birthday>();

  @ViewChild(MatPaginator) set paginator(paginator: MatPaginator) { this.upcomingBirthdays.paginator = paginator; }

  get range(): (size: number, startAt?: number) => number[] { return range; }
  get seasonNames(): Map<number, string> { return seasonNames; }

  constructor(public save: SaveInfoService, private gameInfo: GameInfoService) {
    this.birthdays = gameInfo.villagers
      .map(villager => ({
        villager: villager.name,
        datable: villager.datable,
        day: villager.birthday,
        date: villager.birthDate,
        bestGifts: villager.loves
      }))
      .sort((a, b) => a.date - b.date);
  }

  ngOnInit(): void {
    this.save.updated.subscribe((save: SaveInfo) => {
      this.seasonalItems = [...this.gameInfo.shipping, ...this.gameInfo.fish].filter(item =>
        item.seasons &&
        item.seasons[seasonNames.get(save.currentSeason).toLowerCase()] &&
        !save.collectedItems.includes(item.id) &&
        Object.values(item.seasons).filter(value => value).length < 3);

      this.upcomingBirthdays.data = [
        ...this.birthdays.filter(birthday => birthday.date >= this.save.currentDate),
        ...this.birthdays.filter(birthday => birthday.date < this.save.currentDate)
      ];
    });
  }
}

interface Birthday {
  villager: string;
  datable: boolean;
  day: string;
  date: number;
  bestGifts: Item[];
}

<h1 class="mat-h1">Dashboard</h1>
<div id="container" *ngIf="save.currentDay">
  <mat-card class="birthdays">
    <mat-card-header>
      <mat-card-title>Birthdays</mat-card-title>
    </mat-card-header>
    <mat-card-content>
      <table mat-table [dataSource]="upcomingBirthdays">
        <ng-container matColumnDef="villager">
          <th mat-header-cell *matHeaderCellDef>Villager</th>
          <td mat-cell *matCellDef="let birthday">{{ birthday.villager }}</td>
        </ng-container>
        <ng-container matColumnDef="day">
          <th mat-header-cell *matHeaderCellDef>Date</th>
          <td mat-cell *matCellDef="let birthday">{{ birthday.day }}</td>
        </ng-container>
        <ng-container matColumnDef="bestGifts">
          <th mat-header-cell *matHeaderCellDef>Best Gifts</th>
          <td mat-cell *matCellDef="let birthday" class="best-gifts">
            <app-item-button
              *ngFor="let item of birthday.bestGifts"
              [item]="item"
            ></app-item-button>
          </td>
        </ng-container>
        <ng-container matColumnDef="hearts">
          <th mat-header-cell *matHeaderCellDef>Hearts</th>
          <td mat-cell *matCellDef="let birthday">
            <ul class="hearts">
              <img
                *ngFor="
                  let i of range(save.relationships.get(birthday.villager).maxHearts || 10, 1)
                "
                src="assets/heart-{{
                  save.relationships.get(birthday.villager).hearts >= i
                    ? 'filled'
                    : 'outline'
                }}.png"
              />
            </ul>
          </td>
        </ng-container>

        <tr
          mat-header-row
          *matHeaderRowDef="['villager', 'hearts', 'day', 'bestGifts']"
        ></tr>
        <tr
          mat-row
          *matRowDef="
            let row;
            columns: ['villager', 'hearts', 'day', 'bestGifts']
          "
        ></tr>
      </table>
    </mat-card-content>
    <mat-card-footer>
      <mat-paginator
        [pageSize]="10"
        [pageSizeOptions]="[5, 10, 20, 50]"
        showFirstLastButtons
      ></mat-paginator>
    </mat-card-footer>
  </mat-card>

  <mat-card class="seasonal">
    <mat-card-header>
      <mat-card-title>{{ seasonNames.get(save.currentSeason) }}</mat-card-title>
    </mat-card-header>
    <mat-card-content>
      <div class="seasonal-items">
        <app-item-button *ngFor="let item of seasonalItems" [item]="item" padding></app-item-button>
      </div>
    </mat-card-content>
  </mat-card>
</div>
