// stardew-completionist/src/app/dashboard/dashboard.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { GameInfoService, Item, seasonNames } from '../data/game-info.service';
import { SaveInfo, SaveInfoService } from '../data/save-info.service';
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator } from '@angular/material/paginator';
import { range } from '../friendship/friendship.component';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {
  seasonalItems: Item[];
  birthdays: Birthday[];
  upcomingBirthdays = new MatTableDataSource<Birthday>();

  @ViewChild(MatPaginator) set paginator(paginator: MatPaginator) { this.upcomingBirthdays.paginator = paginator; }

  get range(): (size: number, startAt?: number) => number[] { return range; }
  get seasonNames(): Map<number, string> { return seasonNames; }

  constructor(public save: SaveInfoService, private gameInfo: GameInfoService) {
    this.birthdays = gameInfo.villagers
      .map(villager => ({
        villager: villager.name,
        datable: villager.datable,
        day: villager.birthday,
        date: villager.birthDate,
        bestGifts: villager.loves
      }))
      .sort((a, b) => a.date - b.date);
  }

  ngOnInit(): void {
    this.save.updated.subscribe((save: SaveInfo) => {
      this.seasonalItems = [...this.gameInfo.shipping, ...this.gameInfo.fish].filter(item =>
        item.seasons &&
        item.seasons[seasonNames.get(save.currentSeason).toLowerCase()] &&
        !save.collectedItems.includes(item.id) &&
        Object.values(item.seasons).filter(value => value).length < 3);

      this.upcomingBirthdays.data = [
        ...this.birthdays.filter(birthday => birthday.date >= this.save.currentDate),
        ...this.birthdays.filter(birthday => birthday.date < this.save.currentDate)
      ];
    });
  }
}

interface Birthday {
  villager: string;
  datable: boolean;
  day: string;
  date: number;
  bestGifts: Item[];
}

<h1 class="mat-h1">Dashboard</h1>
<div id="container" *ngIf="save.currentDay">
  <mat-card class="birthdays">
    <mat-card-header>
      <mat-card-title>Birthdays</mat-card-title>
    </mat-card-header>
    <mat-card-content>
      <table mat-table [dataSource]="upcomingBirthdays">
        <ng-container matColumnDef="villager">
          <th mat-header-cell *matHeaderCellDef>Villager</th>
          <td mat-cell *matCellDef="let birthday">{{ birthday.villager }}</td>
        </ng-container>
        <ng-container matColumnDef="day">
          <th mat-header-cell *matHeaderCellDef>Date</th>
          <td mat-cell *matCellDef="let birthday">{{ birthday.day }}</td>
        </ng-container>
        <ng-container matColumnDef="bestGifts">
          <th mat-header-cell *matHeaderCellDef>Best Gifts</th>
          <td mat-cell *matCellDef="let birthday" class="best-gifts">
            <app-item-button
              *ngFor="let item of birthday.bestGifts"
              [item]="item"
            ></app-item-button>
          </td>
        </ng-container>
        <ng-container matColumnDef="hearts">
          <th mat-header-cell *matHeaderCellDef>Hearts</th>
          <td mat-cell *matCellDef="let birthday">
            <ul class="hearts">
              <img
                *ngFor="
                  let i of range(save.relationships.get(birthday.villager).maxHearts || 10, 1)
                "
                src="assets/heart-{{
                  save.relationships.get(birthday.villager).hearts >= i
                    ? 'filled'
                    : 'outline'
                }}.png"
              />
            </ul>
          </td>
        </ng-container>

        <tr
          mat-header-row
          *matHeaderRowDef="['villager', 'hearts', 'day', 'bestGifts']"
        ></tr>
        <tr
          mat-row
          *matRowDef="
            let row;
            columns: ['villager', 'hearts', 'day', 'bestGifts']
          "
        ></tr>
      </table>
    </mat-card-content>
    <mat-card-footer>
      <mat-paginator
        [pageSize]="10"
        [pageSizeOptions]="[5, 10, 20, 50]"
        showFirstLastButtons
      ></mat-paginator>
    </mat-card-footer>
  </mat-card>

  <mat-card class="seasonal">
    <mat-card-header>
      <mat-card-title>{{ seasonNames.get(save.currentSeason) }}</mat-card-title>
    </mat-card-header>
    <mat-card-content>
      <div class="seasonal-items">
        <app-item-button *ngFor="let item of seasonalItems" [item]="item" padding></app-item-button>
      </div>
    </mat-card-content>
  </mat-card>
</div>

// src/pages/Dashboard.svelte
<script lang="ts">
  import "@material/card/dist/mdc.card.min.css";
  import "@material/data-table/dist/mdc.data-table.min.css";
  import "@material/typography/dist/mdc.typography.min.css";
  import type { Readable } from "svelte/store";
  import { derived } from "svelte/store";
  import type { Item, Recipe } from "../game-info";
  import gameInfo from "../game-info";
  import ItemButton from "../ItemButton.svelte";
  import { seasonNames } from "../names";
  import type { SaveGame } from "../save";
  import save from "../save";

  interface Birthday {
    villager: string;
    hearts: number;
    maxHearts: number;
    date: string;
    bestGifts: Item[];
  }

  const birthdays = derived<typeof save, Birthday[]>(
    save,
    ($save: SaveGame | null, set: (value: Birthday[]) => void) => {
      if ($save !== null) {
        set(
          Object.values(gameInfo.villagers)
            .sort(
              (a, b) =>
                ((a.birthDate - $save.currentDate + 112) % 112) -
                ((b.birthDate - $save.currentDate + 112) % 112)
            )
            .map((villager) => ({
              villager: villager.name,
              date: villager.birthday,
              hearts: $save.relationships.get(villager.name)?.hearts ?? 0,
              maxHearts:
                $save.relationships.get(villager.name)?.maxHearts ??
                (villager.datable ? 8 : 10),
              bestGifts: villager.bestGifts,
            }))
        );
      }
    }
  );

  const requiredItems = derived(save, ($save) => {
    if ($save === null) {
      return null;
    } else {
      const output: Record<string, number> = {};

      const recipes: Record<string, number> = {};

      const processRecipe = (recipe: Recipe) => {
        for (const [ingredient, amount] of Object.entries(recipe.ingredients)) {
          const recipe = Object.values(gameInfo.recipes).find(
            (recipe) => recipe.result.id === ingredient
          );
          if (recipe) {
            recipes[recipe.name] ??= 0;
            // If a recipe makes two of an item, you only need to craft it once to satisfy the need for two of the item.
            recipes[recipe.name] += amount / recipe.amount;
            processRecipe(recipe);
          }
        }
      };

      const rootRecipes = Object.values(gameInfo.recipes).filter(
        (recipe) => !$save.collectedItems.includes(recipe.result.id)
      );

      // Figure out all the recipes needed to craft other recipes
      for (const recipe of rootRecipes) {
        processRecipe(recipe);
      }

      // You can't make half a recipe
      for (const recipe in recipes) {
        recipes[recipe] = Math.ceil(recipes[recipe]);
      }

      // Only if you won't be making the recipe anyway should the root recipes be added
      for (const recipe of rootRecipes) {
        recipes[recipe.name] ??= 1;
      }

      for (const [name, recipeAmount] of Object.entries(recipes)) {
        const recipe = gameInfo.recipes[name];
        for (const [ingredient, amount] of Object.entries(recipe.ingredients)) {
          if (
            Object.values(gameInfo.recipes).some(
              (recipe) => recipe.result.id === ingredient
            )
          ) {
            continue;
          }
          output[ingredient] ??= 0;
          output[ingredient] += amount * recipeAmount;
        }
      }

      for (const { id } of gameInfo.shipping) {
        if (!$save.collectedItems.includes(id)) {
          output[id] ??= 0;
          output[id] += 1;
        }
      }

      for (const { id } of gameInfo.fish) {
        if (!$save.collectedItems.includes(id)) {
          output[id] ??= 1;
        }
      }

      for (const bundle of Object.values(gameInfo.bundles)) {
        for (const index in Object.entries(bundle.items)) {
          const item = bundle.items[index];
          if (!$save.bundleCompletion.get(bundle.id)![index]) {
            output[item.id] ??= 0;
            output[item.id] += item.amount;
          }
        }
      }

      for (const id in output) {
        output[id] -= $save.items[id] ?? 0;
        if (output[id] <= 0) delete output[id];
      }

      return output;
    }
  });

  const seasonalItems: Readable<Record<string, number>> = derived(
    requiredItems,
    ($requiredItems, set) => {
      if ($requiredItems !== null) {
        set(
          Object.fromEntries(
            Object.entries($requiredItems).filter(([id, _]) => {
              const item = gameInfo.items[id];
              return (
                item &&
                typeof item.seasons !== "undefined" &&
                item.seasons.includes(
                  ["spring", "summer", "fall", "winter"][$save!.currentSeason]
                ) &&
                Object.values(item.seasons).filter((value) => value).length < 3
              );
            })
          )
        );
      }
    }
  );
</script>

<svelte:head>
  <title>Dashboard | Stardew Completionist</title>
</svelte:head>

<h1 class="title mdc-typography--headline4">Dashboard</h1>
{#if $save !== null}
  <div class="container">
    <div class="mdc-data-table">
      <div class="mdc-data-table__table-container">
        <table class="mdc-data-table__table">
          <thead>
            <tr class="mdc-data-table__header-row">
              <th
                class="mdc-data-table__header-cell"
                role="columnheader"
                scope="col"
              >
                Villager
              </th>
              <th
                class="mdc-data-table__header-cell"
                role="columnheader"
                scope="col"
              >
                Hearts
              </th>
              <th
                class="mdc-data-table__header-cell"
                role="columnheader"
                scope="col"
              >
                Birthday
              </th>
              <th
                class="mdc-data-table__header-cell"
                role="columnheader"
                scope="col"
              >
                Best Gifts
              </th>
            </tr>
          </thead>
          <tbody class="mdc-data-table__content">
            {#each $birthdays as birthday}
              <tr class="mdc-data-table__row">
                <th class="mdc-data-table__cell" scope="row">
                  {birthday.villager}
                </th>
                <td class="mdc-data-table__cell">
                  <div class="hearts">
                    {#each [...Array(birthday.maxHearts).keys()] as i}
                      <img
                        alt="heart"
                        src="./images/heart-{birthday.hearts >= i + 1
                          ? 'filled'
                          : 'outline'}.png"
                      />
                    {/each}
                  </div>
                </td>
                <td class="mdc-data-table__cell">{birthday.date}</td>
                <td class="mdc-data-table__cell">
                  <div class="best-gifts">
                    {#each birthday.bestGifts as item}
                      <ItemButton {item} scale={item.isCraftable ? 1 : 2} />
                    {/each}
                  </div>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    </div>
    <div class="mdc-card mdc-card--outlined seasonal">
      <h2 class="mdc-typography--headline6">
        {seasonNames.get($save.currentSeason)}
      </h2>
      <div class="seasonal-items">
        {#each Object.entries($seasonalItems) as [id, quantity]}
          <ItemButton
            item={gameInfo.items[id]}
            scale={gameInfo.items[id].isCraftable ? 2 : 3}
            {quantity}
          />
        {/each}
      </div>
    </div>
  </div>
{:else}
  <p class="no-save">
    When you select a save file, this section shows information about what you
    should do next.
  </p>
{/if}

<style lang="scss">
  .best-gifts {
    display: flex;
    flex-direction: row;

    :global(button:not(:last-of-type)) {
      margin-right: 8px;
    }
  }

  .hearts {
    display: flex;
    flex-direction: row;

    img {
      user-select: none;

      &:not(:last-of-type) {
        margin-right: 2px;
      }
    }
  }

  .title {
    margin: 20px 20px 0.5em;
  }

  .container {
    display: grid;
    gap: 24px;
    grid-template-areas:
      "b"
      "s";

    @media only screen and (min-width: 1250px) {
      grid-template-areas: "b s";
      grid-template-columns: minmax(0, 1fr) auto;
      grid-template-rows: min-content;
    }

    padding: 0 20px 20px;
  }

  .seasonal {
    display: flex;
    flex-flow: column nowrap;

    grid-area: s;

    padding: 16px;

    .seasonal-items {
      display: grid;
      grid-auto-flow: row;
      grid-auto-rows: 64px;
      grid-template-columns: repeat(auto-fill, 64px);
      gap: 8px;

      flex-grow: 1;

      @media only screen and (min-width: 1250px) {
        grid-template-columns: repeat(2, 64px);
      }
    }
  }

  .no-save {
    margin: 0px 20px;
  }
</style>
