// stardew-completionist/src/app/item-info/item-info.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { MAT_DIALOG_DATA } from '@angular/material/dialog';
import { categories, GameInfoService, Item, locationNames, weatherNames } from '../data/game-info.service';

@Component({
  templateUrl: './item-info.component.html',
  styleUrls: ['./item-info.component.scss']
})
export class ItemInfoComponent implements OnInit {
  item: Item;
  ingredients: {
    id: string;
    name: string;
    quantity: number;
  }[];
  artifactSpots: Map<string, number>;

  get weatherNames(): Map<string, string> { return weatherNames; }

  constructor(@Inject(MAT_DIALOG_DATA) private data: { item: Item }, private gameInfo: GameInfoService) {
    this.item = this.data.item;
    if (this.item.ingredients) {
      this.ingredients = Object.entries(this.item.ingredients).map(value => ({
        id: value[0],
        name: categories.has(value[0]) ? categories.get(value[0]) : this.gameInfo.items.get(value[0]).name,
        quantity: value[1]
      }));
    }
    if (this.item.artifactSpots) {
      this.artifactSpots = new Map(Object.entries(this.item.artifactSpots).map(value => [locationNames.get(value[0]), value[1]]));
    }
  }

  ngOnInit(): void { }
}

<header mat-dialog-title>
  <img src="assets/sprites/{{ item.id }}.png" [alt]="item.name" id="icon" />
  <h1>{{ item.name }}</h1>
  <div id="buttons">
    <a mat-icon-button [href]="item.url" target="_blank">
      <mat-icon>launch</mat-icon>
    </a>
  </div>
</header>
<mat-dialog-content>
  <mat-card *ngIf="item.seasons" class="seasons">
    <mat-card-subtitle>Seasons</mat-card-subtitle>
    <ul>
      <li *ngIf="item.seasons.spring" class="spring">
        <img src="assets/spring.png" />Spring
      </li>
      <li *ngIf="item.seasons.summer" class="summer">
        <img src="assets/summer.png" />Summer
      </li>
      <li *ngIf="item.seasons.fall" class="fall">
        <img src="assets/fall.png" />Fall
      </li>
      <li *ngIf="item.seasons.winter" class="winter">
        <img src="assets/winter.png" />Winter
      </li>
    </ul>
  </mat-card>
  <mat-card
    *ngIf="item.sources || item.monsterDrops || item.artifactSpots"
    class="sources"
  >
    <div *ngIf="item.sources || item.monsterDrops">
      <mat-card-subtitle>Sources</mat-card-subtitle>
      <ul>
        <div *ngIf="item.sources">
          <li *ngFor="let source of item.sources">{{ source }}</li>
        </div>
        <div *ngIf="item.monsterDrops">
          <li *ngFor="let monsterDrop of item.monsterDrops | keyvalue">
            {{ monsterDrop | probability }}
          </li>
        </div>
      </ul>
    </div>
    <div *ngIf="item.artifactSpots">
      <mat-card-subtitle>Artifact Spots</mat-card-subtitle>
      <ul>
        <li *ngFor="let artifactSpot of artifactSpots | keyvalue">
          {{ artifactSpot | probability }}
        </li>
      </ul>
    </div>
  </mat-card>

  <mat-card *ngIf="item.ingredients" class="ingredients">
    <mat-card-subtitle>Ingredients</mat-card-subtitle>
    <ul>
      <li *ngFor="let item of ingredients">
        {{ item.name }}
        <span *ngIf="item.quantity > 1"> × {{ item.quantity }}</span>
      </li>
    </ul>

    <div *ngIf="item.recipeSources">
      <mat-card-subtitle>Recipe Sources</mat-card-subtitle>
      <ul>
        <li *ngFor="let source of item.recipeSources">{{ source }}</li>
      </ul>
    </div>
  </mat-card>

  <mat-card *ngIf="item.locations" class="location">
    <mat-card-subtitle>Found in</mat-card-subtitle>
    <ul>
      <li *ngFor="let location of item.locations">{{ location }}</li>
    </ul>
    <span
      *ngIf="item.time && !(item.time[0] == '600' && item.time[1] == '2600')"
      >{{ item.time[0] | time }} – {{ item.time[1] | time }}<br
    /></span>

    <span *ngIf="item.weather && item.weather != 'both'">{{
      weatherNames.get(item.weather)
    }}</span>
  </mat-card>
</mat-dialog-content>

// src/components/ItemInfo.svelte
<script lang="ts">
  import IconButton from '@smui/icon-button';
  import gameInfo from '../game-info';
  import type { Item } from '../game-info';
  import { categories, locationNames, weatherNames } from '../names';

  export let item: Item;

  function calcProbability(probability: number): number {
    return Math.round((probability + Number.EPSILON) * 10000000) / 100000;
  }
</script>

<style lang="scss">
  @use "@material/card";
  @use "@material/typography/mixins" as *;

  @include card.core-styles;

  .mdc-dialog__title {
    padding-right: 0;
  }

  .header {
    display: inline-flex;
    align-items: center;

    width: 100%;
    height: 100%;
    padding: 8px 8px 8px 0;

    :global(:last-child) {
      display: inline-block;
      vertical-align: middle;

      margin-left: auto;
    }

    img {
      display: inline-block;
      vertical-align: middle;

      image-rendering: crisp-edges;
      image-rendering: pixelated;

      margin-right: 8px;
    }
  }

  .content {
    display: grid;
    gap: 16px;
    grid-auto-columns: repeat(max(2), auto);

    .seasons {
      ul {
        list-style-type: none;

        img {
          position: relative;
          top: 3px;
          margin-right: 8px;
        }
      }
    }

    .section {
      padding: 16px;

      h2 {
        margin: 0;

        @include typography("subtitle2");

        &:not(:first-of-type) {
          margin-top: 8px;
        }
      }

      ul {
        @include typography("body2");
        color: black;

        margin: 0;
        padding: 0;
        list-style-position: inside;
      }

      p {
        @include typography("body2");
        color: black;

        margin: 0;
        padding: 0;

        img {
          position: relative;
          top: 3px;
          margin-right: 4px;
        }
      }
    }
  }
</style>

{#if typeof item !== 'undefined'}
  <div class="mdc-dialog__title">
    <div class="header">
      <img
        class="dialog-icon"
        src="data:image/png;base64,{item.sprite}"
        alt={item.name}
        height={item.isCraftable ? 64 : 48} />
      {item.name}
      <IconButton class="material-icons" href={item.url} target="_blank">
        launch
      </IconButton>
    </div>
  </div>
  <div class="mdc-dialog__content content">
    {#if typeof item.seasons !== 'undefined'}
      <div class="mdc-card section section seasons">
        <h2>Seasons</h2>
        <ul>
          {#if item.seasons.includes('spring')}
            <li>
              <img src="spring.png" alt="Spring" />
              Spring
            </li>
          {/if}
          {#if item.seasons.includes('summer')}
            <li>
              <img src="summer.png" alt="Summer" />
              Summer
            </li>
          {/if}
          {#if item.seasons.includes('fall')}
            <li>
              <img src="fall.png" alt="Fall" />
              Fall
            </li>
          {/if}
          {#if item.seasons.includes('winter')}
            <li>
              <img src="winter.png" alt="Winter" />
              Winter
            </li>
          {/if}
        </ul>
      </div>
    {/if}

    {#if typeof item.sources !== 'undefined' || typeof item.monsterDrops !== 'undefined' || typeof item.artifactSpots !== 'undefined'}
      <div class="mdc-card section">
        {#if typeof item.sources !== 'undefined' || typeof item.monsterDrops !== 'undefined'}
          <h2>Sources</h2>
          <ul>
            {#if typeof item.sources !== 'undefined'}
              {#each item.sources as source}
                <li>{source}</li>
              {/each}
            {/if}
            {#if typeof item.monsterDrops !== 'undefined'}
              {#each Object.entries(item.monsterDrops) as [monster, probability]}
                <li>{monster} ({calcProbability(probability)}%)</li>
              {/each}
            {/if}
          </ul>
        {/if}

        {#if typeof item.artifactSpots !== 'undefined'}
          <h2>Artifact Spots</h2>
          <ul>
            {#each Object.entries(item.artifactSpots) as [location, probability]}
              <li>
                {locationNames.get(location)} ({calcProbability(probability)}%)
              </li>
            {/each}
          </ul>
        {/if}
      </div>
    {/if}

    {#if typeof item.ingredients !== 'undefined'}
      <div class="mdc-card section">
        <h2>Ingredients</h2>
        <ul>
          {#each Object.entries(item.ingredients) as [id, quantity]}
            <li>
              {categories.get(id) || gameInfo.items[id].name}
              {#if quantity > 1}× {quantity}{/if}
            </li>
          {/each}
        </ul>

        {#if typeof item.recipeSources !== 'undefined'}
          <h2>Recipe Sources</h2>
          <ul>
            {#each item.recipeSources as source}
              <li>{source}</li>
            {/each}
          </ul>
        {/if}
      </div>
    {/if}

    {#if typeof item.locations !== 'undefined'}
      <div class="mdc-card section">
        <h2>Found in</h2>
        <ul>
          {#each item.locations as location}
            <li>{location}</li>
          {/each}
        </ul>
        {#if typeof item.time !== 'undefined' && item.time !== '6AM – 2AM'}
          <p>{item.time}</p>
        {/if}
        {#if typeof item.weather !== 'undefined' && item.weather !== 'both'}
          <p>
            <img
              src="{item.weather}.png"
              alt={weatherNames.get(item.weather)} />
            {weatherNames.get(item.weather)}
          </p>
        {/if}
      </div>
    {/if}
  </div>
{/if}
