// src/pages/Friendship.svelte
<script lang="ts">
  import "@material/data-table/dist/mdc.data-table.min.css";
  import "@material/typography/dist/mdc.typography.min.css";
  import { derived } from "svelte/store";
  import ItemButton from "../ItemButton.svelte";
  import type { Villager } from "../game-info";
  import save from "../save";
  import type { Relationship } from "../save";
  import gameInfo from "../game-info";

  let villagers = derived<typeof save, (Villager & Relationship)[]>(
    save,
    ($save) =>
      Object.values(gameInfo.villagers)
        .map((villager) => ({
          ...villager,

          // These will be overriden by relationship, but will serve as backup if they haven't yet been met
          hearts: 0,
          maxHearts: villager.datable ? 8 : 10,
          giftsThisWeek: 0,

          ...$save?.relationships.get(villager.name),
        }))
        .sort((a, b) => a.hearts - b.hearts)
  );
</script>

<svelte:head>
  <title>Friendship | Stardew Completionist</title>
</svelte:head>

<h1 class="mdc-typography--headline4">Friendship</h1>
<div class="mdc-data-table">
  <div class="mdc-data-table__table-container">
    <table class="mdc-data-table__table" aria-label="Dessert calories">
      <thead>
        <tr class="mdc-data-table__header-row">
          <th
            class="mdc-data-table__header-cell"
            role="columnheader"
            scope="col"
          >
            Villager
          </th>
          {#if $save !== null}
            <th
              class="mdc-data-table__header-cell"
              role="columnheader"
              scope="col"
            >
              Hearts
            </th>
          {/if}
          <th
            class="mdc-data-table__header-cell"
            role="columnheader"
            scope="col"
          >
            Birthday
          </th>
          <th
            class="mdc-data-table__header-cell"
            role="columnheader"
            scope="col"
          >
            Best Gifts
          </th>
        </tr>
      </thead>
      <tbody class="mdc-data-table__content">
        {#each $villagers.filter((villager) => typeof villager.hearts === "undefined" || villager.hearts < villager.maxHearts) as villager}
          <tr class="mdc-data-table__row">
            <th class="mdc-data-table__cell" scope="row">{villager.name}</th>
            {#if $save !== null}
              <td class="mdc-data-table__cell">
                <div class="hearts">
                  {#each [...Array(villager.maxHearts).keys()] as i}
                    <img
                      alt="heart"
                      src="./images/heart-{villager.hearts >= i + 1
                        ? 'filled'
                        : 'outline'}.png"
                    />
                  {/each}
                </div>
              </td>
            {/if}
            <td class="mdc-data-table__cell">{villager.birthday}</td>
            <td class="mdc-data-table__cell">
              <div class="best-gifts">
                {#each villager.bestGifts as item}
                  <ItemButton {item} scale={item.isCraftable ? 1 : 2} />
                {/each}
              </div>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>

<style lang="scss">
  h1 {
    margin: 20px 20px 0.5em;
  }

  .mdc-data-table {
    margin: 0px 24px 24px;
  }

  .best-gifts {
    display: flex;
    flex-direction: row;

    :global(button:not(:last-of-type)) {
      margin-right: 8px;
    }
  }

  .hearts {
    display: flex;
    flex-direction: row;

    img {
      user-select: none;

      &:not(:last-of-type) {
        margin-right: 2px;
      }
    }
  }
</style>

// stardew-completionist/src/app/friendship/friendship.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { MatSort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { GameInfoService } from '../data/game-info.service';
import { SaveInfoService } from '../data/save-info.service';

export const range = (size: number, startAt = 0): number[] => [...Array(size).keys()].map(i => i + startAt);

@Component({
  selector: 'app-friendship',
  templateUrl: './friendship.component.html',
  styleUrls: ['./friendship.component.scss']
})
export class FriendshipComponent implements OnInit {
  shownColumns = ['name', 'birthday', 'bestGifts'];
  villagers = new MatTableDataSource(this.gameInfo.villagers);

  get range(): (size: number, startAt?: number) => number[] { return range; }

  @ViewChild(MatSort, { static: true }) set sort(value: MatSort) { this.villagers.sort = value; }

  constructor(public gameInfo: GameInfoService, save: SaveInfoService) {
    this.villagers.sortingDataAccessor = (data, id) => {
      switch (id) {
        case 'birthday':
          return data.birthDate;
        case 'hearts':
          return data.relationship?.hearts;
        default:
          return data[id] as string | number;
      }
    };

    save.updated.subscribe(() => {
      this.shownColumns = ['name', 'hearts', 'birthday', 'bestGifts'];
      this.villagers.data = this.gameInfo.villagers
        .filter(villager => villager.relationship?.hearts < villager.relationship?.maxHearts);
    });
  }

  ngOnInit(): void { }
}

<h1>Friendship</h1>

<mat-card>
  <table mat-table [dataSource]="villagers" matSort matSortActive="hearts" matSortDirection="asc">
    <ng-container matColumnDef="name">
      <th mat-header-cell *matHeaderCellDef mat-sort-header>Villager</th>
      <td mat-cell *matCellDef="let villager">{{ villager.name }}</td>
    </ng-container>
    <ng-container matColumnDef="bestGifts">
      <th mat-header-cell *matHeaderCellDef>Best Gifts</th>
      <td mat-cell *matCellDef="let villager" class="best-gifts">
        <app-item-button
          *ngFor="let item of villager.loves"
          [item]="item"
        ></app-item-button>
      </td>
    </ng-container>
    <ng-container matColumnDef="hearts">
      <th mat-header-cell *matHeaderCellDef mat-sort-header>Hearts</th>
      <td mat-cell *matCellDef="let villager">
        <ul class="hearts">
          <img
            *ngFor="let i of range(villager.relationship?.maxHearts || 10, 1)"
            src="assets/heart-{{
              villager.relationship?.hearts >= i ? 'filled' : 'outline'
            }}.png"
          />
        </ul>
      </td>
    </ng-container>
    <ng-container matColumnDef="birthday">
      <th mat-header-cell *matHeaderCellDef mat-sort-header>Birthday</th>
      <td mat-cell *matCellDef="let villager">{{ villager.birthday }}</td>
    </ng-container>

    <tr mat-header-row *matHeaderRowDef="shownColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: shownColumns"></tr>
  </table>
</mat-card>
